// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocrhwawoafnudgmyvlno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcmh3YXdvYWZudWRnbXl2bG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTkyNTYsImV4cCI6MjA1NDkzNTI1Nn0.0Tp_PXQx9ev8K1t_bqDNUSzfrukWHYaF2p5YoK3y83Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);